# Generated by Django 5.1.3 on 2024-11-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Coin Name')),
                ('year', models.IntegerField(verbose_name='Year of Issue')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coin Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Coin Image')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Country Name')),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Antarctica', 'Antarctica'), ('Australia', 'Australia')], max_length=20, verbose_name='Continent')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Material Price')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('location', models.CharField(max_length=255, verbose_name='Shop Location')),
                ('contact_info', models.CharField(default='No Info', max_length=255, verbose_name='Contact Info')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('coins', models.ManyToManyField(blank=True, to='coindb.coin', verbose_name='Collected Coins')),
            ],
            options={
                'verbose_name': 'Collector',
                'verbose_name_plural': 'Collectors',
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coindb.country', verbose_name='Country of Origin'),
        ),
        migrations.AddField(
            model_name='coin',
            name='material',
            field=models.ManyToManyField(to='coindb.material', verbose_name='Coin Material'),
        ),
    ]
