# Generated by Django 4.2.16 on 2024-11-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coindb', '0002_coin_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='image',
            new_name='imageObverse',
        ),
        migrations.AddField(
            model_name='coin',
            name='imageReverse',
            field=models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Coin Image'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coindb.country', verbose_name='Country of Origin'),
        ),
    ]
