# Generated by Django 4.2.16 on 2024-11-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coindb', '0003_rename_image_coin_imageobverse_coin_imagereverse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='imageObverse',
            field=models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Coin Obverse Image'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='imageReverse',
            field=models.ImageField(blank=True, null=True, upload_to='coins/', verbose_name='Coin Reverse Image'),
        ),
    ]
