# Generated by Django 4.2.16 on 2024-11-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coindb', '0004_alter_coin_imageobverse_alter_coin_imagereverse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collector',
        ),
    ]
