# Generated by Django 4.2.16 on 2024-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coindb', '0006_coincollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='coindb.material', verbose_name='Coin Material'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Issue'),
        ),
    ]
